Add blank index file
oracleot/embedding-images-and-videos pull request #1
Opened 2020-07-07 14:20 UTC by jrai0792

Have added blank index.html file.

2020-07-07 14:22 UTC, oracleot commented
I verified the pull request with the added blank index.html file

2020-07-10 11:04 UTC, HADDADSOHAIB requested changes
### Status: Change required :recycle: 

### Hi @jrai0792 and @oracleot :hand: 

### Great job with the project, you did great work. There is some changes to be made to approve the project:
- check my comments for additional requirements.
- In the project description, there was a link that you should have used to build your project:
![image](https://user-images.githubusercontent.com/26064042/87140678-cf2f7480-c299-11ea-8a7f-90c8b7b99024.png)
http://archive.vn/Bss88
there a slight different between your project and that link in the section under the main video.

 | Source Page	| Clone Page |
|:---:|:---:|
|![Screenshot from 2020-07-10 11-51-12](https://user-images.githubusercontent.com/26064042/87147021-cd6aae80-c2a3-11ea-80bf-744427897f73.png) |![Screenshot from 2020-07-10 11-50-59](https://user-images.githubusercontent.com/26064042/87147036-d22f6280-c2a3-11ea-9dea-c69eb0bbb4e7.png) |

- A pull request description should have information about what this pull request add to the project.
![Screenshot from 2020-07-10 12-01-48](https://user-images.githubusercontent.com/26064042/87147841-428ab380-c2a5-11ea-9922-3ae9c169ed56.png)
Please improve the current description

### Once done with the changes, ask for another code review.

2020-07-10 11:04 UTC, HADDADSOHAIB commented on index.html
> +          <i class="fa fa-share" aria-hidden="true"></i>&ensp;Share&emsp;
The share icon should be a button

2020-07-10 11:51 UTC, oracleot commented on index.html
> +          <i class="fa fa-share" aria-hidden="true"></i>&ensp;Share&emsp;
Thanks for the code review, we will resolve ASAP and ask for another review

2020-07-10 13:27 UTC, jrai0792 commented on index.html
> +          <i class="fa fa-share" aria-hidden="true"></i>&ensp;Share&emsp;
Code revamped based on the feedback from the code review.

2020-07-13 08:57 UTC, peterrobert requested changes
### CHANGES REQIRED :recycle: :stop_button: 
### HELLO @jrai0792 AND @oracleot AM PETER ROBERT A TSE AND I HAVE REVIEWED YOUR PROJECT. 
### YOUR PROJECT LOOKS AMAZING :clap:  VERY NICE WORK :partying_face: HOWEVER, THERE ARE A FEW THINGS THAT HAVE PREVENTED ME FROM APPROVING THIS PROJECT KINDLY CHECK BELOW :arrow_down: 

- [x] Just like stated above you need to make sure you have a descriptive pull request message. You can do this by adding a title and a summary of what you have worked on using bullet points.

- [x] Also you do have a readme file :clap: but let us make it more descriptive by adding more information to it. For example, you can add a screenshot of your project.

### when you are done improving on this kindly submit your project for another review. 
### good work working on the changes that were requested by the previous TSE :clap: 

### HAPPY CODING :computer:

2020-07-13 09:42 UTC, peterrobert approved these changes
### APPROVED :+1: :1st_place_medal: 
### VERY IMPRESSIVE WORK YOUR PROJECT IS NOW APPROVED .. GOOD WORK IMPROVING AS REQUESTED :clap: 

[OPTIONAL]
your HTML is showing some warnings when validated by this  [tool](https://validator.w3.org/nu/#textarea) you guys can try and fix the warnings. However, since they are not errors this is not a requirement

### HAPPY CODING :computer:

2020-07-13 10:37 UTC, oracleot commented
Thanks @peterrobert!

2020-07-13 10:56 UTC, merged